/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package pokerApp.iu;

import java.util.ArrayList;
import pokerApp.Fachada.Fachada;
import pokerApp.juego.Mesa;
import pokerApp.usuarios.Sesion;

/**
 *
 * @author maximiliano
 */
public class AdministradorUI extends javax.swing.JDialog {

    private Sesion sesion;

    
    public AdministradorUI(java.awt.Frame parent, boolean modal, Sesion sesion) {
        super(parent, false);
        initComponents();
        this.sesion = sesion;
        setTitle("Administrador - " + sesion.getUsuario().getNombreCompleto());
        
    }

    AdministradorUI(Sesion sesion) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAdministrador = new javax.swing.JLabel();
        btnCrearMesa = new javax.swing.JButton();
        btnAdministrarMesa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblAdministrador.setText("Bienvenido");

        btnCrearMesa.setText("Crear Mesa");
        btnCrearMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearMesaActionPerformed(evt);
            }
        });

        btnAdministrarMesa.setText("Administrar Mesa");
        btnAdministrarMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdministrarMesaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAdministrarMesa)
                    .addComponent(btnCrearMesa)
                    .addComponent(lblAdministrador))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblAdministrador)
                .addGap(37, 37, 37)
                .addComponent(btnAdministrarMesa)
                .addGap(28, 28, 28)
                .addComponent(btnCrearMesa)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearMesaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearMesaActionPerformed

    private void btnAdministrarMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdministrarMesaActionPerformed
 
        ArrayList<Mesa> mesas = Fachada.getInstancia().getMesas();
        AdministrarMesa administrarMesa = new AdministrarMesa(null,false,mesas);
          
    }//GEN-LAST:event_btnAdministrarMesaActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdministrarMesa;
    private javax.swing.JButton btnCrearMesa;
    private javax.swing.JLabel lblAdministrador;
    // End of variables declaration//GEN-END:variables
}
